# Generated by Django 3.2.9 on 2021-11-15 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_alter_account_id_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='id_client',
            field=models.IntegerField(db_index=True, unique=True, verbose_name='user_id'),
        ),
    ]
